/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geocode */
        get: operations["geocode_api_v1_geocode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return readiness information without probing or launching SFINCS.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rainfall/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rainfall Event */
        get: operations["rainfall_event_api_v1_rainfall_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rainfall/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rainfall Stations */
        get: operations["rainfall_stations_api_v1_rainfall_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rainfall/stations/{station_id}/extremes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rainfall Station Extremes */
        get: operations["rainfall_station_extremes_api_v1_rainfall_stations__station_id__extremes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EngineSummary */
        EngineSummary: {
            /**
             * Required
             * @default SFINCS 2.4.0 Galibier
             * @constant
             */
            required: "SFINCS 2.4.0 Galibier";
        };
        /** GeocodeAttribution */
        GeocodeAttribution: {
            /** Text */
            text: string;
            /** Url */
            url: string;
        };
        /** GeocodeCandidateResponse */
        GeocodeCandidateResponse: {
            /** Confidence */
            confidence?: number | null;
            /** Converted */
            converted?: string | null;
            /** Lat */
            lat: number;
            /** Level */
            level?: number | null;
            /** Lon */
            lon: number;
            /**
             * Provider
             * @constant
             */
            provider: "csis_simple_geocoding";
            /** Title */
            title: string;
        };
        /** GeocodeResponse */
        GeocodeResponse: {
            attribution: components["schemas"]["GeocodeAttribution"];
            /** Candidates */
            candidates: components["schemas"]["GeocodeCandidateResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Api Version
             * @default v1
             * @constant
             */
            api_version: "v1";
            /** Application Version */
            application_version: string;
            engine: components["schemas"]["EngineSummary"];
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** RainfallEventResponse */
        RainfallEventResponse: {
            /** Catalog Generated At Utc */
            catalog_generated_at_utc: string;
            /** Data Quality Flags */
            data_quality_flags: string[];
            /** Duration Minutes */
            duration_minutes: number;
            /** Event Date Or Datetime Metadata */
            event_date_or_datetime_metadata?: string | null;
            /** Event Id */
            event_id: string;
            /** Intensity Mm Per H */
            intensity_mm_per_h: number;
            /** Profile Available */
            profile_available: boolean;
            /** Profile Id */
            profile_id?: string | null;
            /** Rank */
            rank?: number | null;
            /** Source Url */
            source_url: string;
            /** Station Id */
            station_id: string;
            /** Station Lat Deg */
            station_lat_deg: number;
            /** Station Lon Deg */
            station_lon_deg: number;
            /** Station Name */
            station_name: string;
            /** Total Precipitation Mm */
            total_precipitation_mm: number;
        };
        /** RainfallExtremesResponse */
        RainfallExtremesResponse: {
            /** Events */
            events: components["schemas"]["RainfallEventResponse"][];
            station: components["schemas"]["RainfallStationResponse"];
        };
        /** RainfallStationResponse */
        RainfallStationResponse: {
            /** Distance Km */
            distance_km?: number | null;
            /** Lat Deg */
            lat_deg: number;
            /** Lon Deg */
            lon_deg: number;
            /** Name */
            name: string;
            /** Prefecture Or Region */
            prefecture_or_region?: string | null;
            /** Station Id */
            station_id: string;
        };
        /** RainfallStationSearchResponse */
        RainfallStationSearchResponse: {
            /** Stations */
            stations: components["schemas"]["RainfallStationResponse"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    geocode_api_v1_geocode_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    rainfall_event_api_v1_rainfall_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RainfallEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rainfall_stations_api_v1_rainfall_stations_get: {
        parameters: {
            query: {
                lon: number;
                lat: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RainfallStationSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rainfall_station_extremes_api_v1_rainfall_stations__station_id__extremes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RainfallExtremesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
